/**
 * generate-fluent-icons.ts
 *
 * Scans SCSS source for `fluent-icon-by-name("icon-name", ...)` and
 * `fluent-icon-content-by-name("icon-name", ...)`, plus
 * `fluent-icons.json` (manual overrides), resolves SVG data from one or more
 * Iconify JSON collections, and generates `_fluent-icons.scss` with:
 *   - `$fluent-icons` SCSS map for name-based resolution
 *   - `$fluent-icon-*` SCSS variables for backward compatibility
 *
 * Supported names:
 *   - `person-20-regular`        → defaults to `fluent:person-20-regular`
 *   - `fluent:person-20-regular` → explicit default collection
 *   - `fluent-mdl2:accept`       → alternate collection
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, "../..");

const ICONIFY_COLLECTIONS = {
  fluent: path.resolve(REPO_ROOT, "node_modules/@iconify-json/fluent/icons.json"),
  "fluent-mdl2": path.resolve(REPO_ROOT, "node_modules/@iconify-json/fluent-mdl2/icons.json"),
} as const;
const DEFAULT_COLLECTION = "fluent";
const SCSS_DIR = path.resolve(REPO_ROOT, "src/scss");
const GENERATED_PATH = path.resolve(SCSS_DIR, "_fluent-icons.scss");
const OUTPUT_HEADER = "// Auto-generated by src/script/generate-fluent-icons.ts — do not edit\n// biome-ignore format: generated file\n\n";

type IconCollectionName = keyof typeof ICONIFY_COLLECTIONS;

type IconEntry = {
  body: string;
  width?: number;
  height?: number;
};

interface IconifyData {
  prefix: string;
  icons: Record<string, IconEntry>;
}

interface ResolvedIconName {
  collection: IconCollectionName;
  icon: string;
  canonical: string;
  aliases: string[];
}

function enc(str: string): string {
  return str.replace(/#/g, "%23");
}

function toSvg(icon: IconEntry): string {
  const w = icon.width ?? 20;
  const h = icon.height ?? 20;
  // Strip fill attributes — mask icons get their color from CSS background,
  // so baked-in fill colors are dead weight and may differ per theme.
  const inner = icon.body.replace(/\s*fill\s*=\s*(["']).*?\1/g, " fill='currentColor'");
  return `<svg xmlns='http://www.w3.org/2000/svg' width='${w}' height='${h}' viewBox='0 0 ${w} ${h}' fill='none'>${inner}</svg>`;
}

function esc(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function varName(iconName: string): string {
  return `fluent-icon-${iconName.replace(/[^a-z0-9-]+/gi, "-")}`;
}

function isIconCollectionName(value: string): value is IconCollectionName {
  return value in ICONIFY_COLLECTIONS;
}

function resolveIconName(rawName: string): ResolvedIconName {
  const trimmed = rawName.trim();
  const idx = trimmed.indexOf(":");

  if (idx === -1) {
    return {
      collection: DEFAULT_COLLECTION,
      icon: trimmed,
      canonical: `${DEFAULT_COLLECTION}:${trimmed}`,
      aliases: [trimmed, `${DEFAULT_COLLECTION}:${trimmed}`],
    };
  }

  const prefix = trimmed.slice(0, idx);
  const icon = trimmed.slice(idx + 1);

  if (!isIconCollectionName(prefix)) {
    throw new Error(`Unsupported icon collection "${prefix}" in "${rawName}". Supported: ${Object.keys(ICONIFY_COLLECTIONS).join(", ")}`);
  }

  return {
    collection: prefix,
    icon,
    canonical: `${prefix}:${icon}`,
    aliases: prefix === DEFAULT_COLLECTION ? [icon, `${prefix}:${icon}`] : [`${prefix}:${icon}`],
  };
}

function loadIconifyCollections(): Record<IconCollectionName, IconifyData> {
  const loaded = {} as Record<IconCollectionName, IconifyData>;
  for (const [name, file] of Object.entries(ICONIFY_COLLECTIONS) as Array<[IconCollectionName, string]>) {
    if (!fs.existsSync(file)) {
      throw new Error(`@iconify-json/${name} not found at ${file}`);
    }
    loaded[name] = JSON.parse(fs.readFileSync(file, "utf-8")) as IconifyData;
  }
  return loaded;
}

function walkScssFiles(dir: string): string[] {
  const result: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      result.push(...walkScssFiles(fullPath));
    } else if (entry.name.startsWith("_") && entry.name.endsWith(".scss") && entry.name !== "_fluent-icons.scss") {
      result.push(fullPath);
    }
  }
  return result;
}

function extractNamesFromScss(content: string): string[] {
  const seen = new Set<string>();

  // Existing mixin matches
  const re = /fluent-(?:icon|mask-icon)(?:-content)?-by-name\s*\(\s*["']([^"']+)["']\s*,/g;
  for (const match of content.matchAll(re)) {
    seen.add(match[1]);
  }

  // Custom __icon__(...) matches
  const reCustom = /__icon__\(\s*["']?([^"'\)]+)["']?\s*\)/g;
  for (const match of content.matchAll(reCustom)) {
    seen.add(match[1]);
  }

  return [...seen].sort();
}

function scanScssForIconNames(): string[] {
  if (!fs.existsSync(SCSS_DIR)) return [];
  const files = walkScssFiles(SCSS_DIR);
  const seen = new Set<string>();
  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8");
    for (const name of extractNamesFromScss(content)) {
      seen.add(name);
    }
  }
  return [...seen].sort();
}

function generateScss(names: string[], collections: Record<IconCollectionName, IconifyData>): string {
  const mapEntries = new Map<string, string>();
  const varEntries = new Map<string, string>();
  const errors: string[] = [];

  for (const rawName of names) {
    let resolved: ResolvedIconName;
    try {
      resolved = resolveIconName(rawName);
    } catch (error) {
      const msg = `⚠ ${(error as Error).message}, skipping`;
      errors.push(msg);
      console.error(`✖ ${msg}`);
      continue;
    }

    const icon = collections[resolved.collection].icons[resolved.icon];
    if (!icon) {
      const msg = `⚠ "${resolved.canonical}" — not found in @iconify-json/${resolved.collection}, skipping`;
      errors.push(msg);
      console.warn(`✖ ${msg}`);
      continue;
    }

    const svg = enc(toSvg(icon));
    const quoted = `"${esc(svg)}"`;

    for (const alias of resolved.aliases) {
      mapEntries.set(alias, quoted);
    }

    varEntries.set(varName(resolved.canonical), quoted);
    if (resolved.collection === DEFAULT_COLLECTION) {
      varEntries.set(varName(resolved.icon), quoted);
    }
  }

  const lines: string[] = [OUTPUT_HEADER];

  if (varEntries.size > 0) {
    lines.push("// ── Backward-compatible variables ──");
    lines.push(...[...varEntries.entries()].map(([name, value]) => `$${name}: ${value};`));
    lines.push("");
  }

  if (mapEntries.size > 0) {
    lines.push("// ── Name-based icon map (for fluent-icon-by-name) ──");
    lines.push("$fluent-icons: (");
    lines.push([...mapEntries.entries()].map(([name, value]) => `  \"${name}\": ${value}`).join(",\n"));
    lines.push(") !default;");
    lines.push("");
  }

  if (errors.length > 0) {
    lines.push("// ⚠ Issues:");
    lines.push(...errors.map((error) => `// ${error}`));
  }

  return lines.join("\n");
}

export function generateIcons(): boolean {
  let collections: Record<IconCollectionName, IconifyData>;
  try {
    collections = loadIconifyCollections();
  } catch (error) {
    console.error(`✖ ${(error as Error).message}`);
    return false;
  }

  const merged = scanScssForIconNames();
  if (merged.length > 0) {
    console.log(`  Found ${merged.length} icon name(s) in SCSS source`);
  }

  if (merged.length === 0) {
    console.warn("  ⚠ No icons to generate — nothing in SCSS source");
    if (!fs.existsSync(path.dirname(GENERATED_PATH))) {
      fs.mkdirSync(path.dirname(GENERATED_PATH), { recursive: true });
    }
    fs.writeFileSync(GENERATED_PATH, `${OUTPUT_HEADER}// No icons configured\n`, "utf-8");
    return true;
  }

  const scss = generateScss(merged, collections);
  const dir = path.dirname(GENERATED_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  if (fs.existsSync(GENERATED_PATH)) {
    const existing = fs.readFileSync(GENERATED_PATH, "utf-8");
    if (existing === scss) {
      console.log(`  ${GENERATED_PATH} — unchanged, skipped`);
      return true;
    }
  }

  fs.writeFileSync(GENERATED_PATH, scss, "utf-8");
  console.log(`✓ Generated ${GENERATED_PATH} (${merged.length} icons)`);
  return true;
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  const ok = generateIcons();
  process.exit(ok ? 0 : 1);
}
