export const FLUENT_DEFAULTS = {
  mode: "auto",
  primary: "#024AD8",
  dark_primary: "#9058FC",
  progressbar_font: "#1A1A1A",
  dark_progressbar_font: "#EEF1FF",
  page_bg: "#F2FBFF",
  card_bg: "#FFFFFF",
  sidebar_bg: "#FFFFFF",
  dark_page_bg: "#080B12",
  dark_card_bg: "#101622",
  dark_sidebar_bg: "#0B0F18",
  font_weight: "normal",
  font_size: "14",
  border_radius: "8",
  control_height: "36",
  sidebar_width: "260",
  header_height: "58",
  login_bg: "microsoft",
  blur: "40",
  transparency: "0.8",
  blur_dark: "20",
  transparency_dark: "0.8",
  card_shadow: "small",
  transition_speed: "normal",
  custom_css: "",
  custom_select: "1",
  view_transition: "1",
  tab_animation: "1",
  prefers_reduced_motion: "1",
  loading_bar: "1",
  sticky_action_bar: "1",
  uci_changes_preview: "1",
  direction_mode: "auto",
  progressbar_text_position: "top-start",
} as const;

export const fluentFlagDefault = (value: string): boolean => value === "1";
