import { defineConfig, rspack } from "@rsbuild/core";
import { pluginSass } from "@rsbuild/plugin-sass";
import { type Compiler, SwcJsMinimizerRspackPlugin } from "@rspack/core";

const luciRequires = `"use strict";
"require view";
"require dom";
"require poll";
"require rpc";
"require network";
`;
const minify = process.env.RSBUILD_MINIFY === "true" || process.env.RSBUILD_MINIFY === "1";
const outputRoot = "../package/luci-mod-fluentdashboard/htdocs/luci-static/resources";

export default defineConfig({
  environments: {
    dashboardJs: {
      source: {
        entry: {
          "view/fluentdashboard/index": "./web/fluentdashboard/index.tsx",
        },
        tsconfigPath: "./tsconfig.json",
      },
      output: {
        module: true,
        charset: "ascii",
        overrideBrowserslist: ["defaults", "not ie <= 11", "not op_mini all", "chrome >= 125", "firefox >= 147", "safari >= 26", "edge >= 125"],
        distPath: {
          root: outputRoot,
          js: ".",
        },
        filename: {
          js: "[name].js",
        },
        assetPrefix: "",
        minify,
        cleanDistPath: false,
      },
      tools: {
        htmlPlugin: false,
        swc: {
          jsc: {
            parser: {
              syntax: "typescript",
              tsx: true,
              decorators: true,
            },
            transform: {
              react: {
                runtime: "automatic",
                importSource: "@lazulikao/luci-types",
                useBuiltins: true,
              },
              optimizer: {
                simplify: true,
              },
            },
            minify: {
              compress: true,
              mangle: {},
            },
          },
        },
        rspack: (config) => {
          config.output = config.output || {};
          config.optimization = config.optimization || {};
          config.optimization.splitChunks = false;
          config.optimization.runtimeChunk = false;
          config.optimization.avoidEntryIife = true;
          config.optimization.usedExports = false;
          config.optimization.sideEffects = false;
          config.plugins = config.plugins || [];

          if (minify) {
            config.optimization.minimizer = [
              new SwcJsMinimizerRspackPlugin({
                minimizerOptions: {
                  module: true,
                  compress: true,
                  mangle: { reserved: ["main"] },
                },
              }),
            ];
            config.plugins.push({
              name: "AddDashboardLuCIWrapperPlugin",
              apply(compiler: Compiler) {
                compiler.hooks.emit.tapAsync("AddDashboardLuCIWrapperPlugin", (compilation, callback) => {
                  for (const name of Object.keys(compilation.assets)) {
                    if (!name.endsWith(".js")) continue;
                    const sourceEdit = `${luciRequires}${compilation.assets[name].source()}\nreturn main;`;
                    compilation.assets[name] = {
                      source: () => sourceEdit,
                      buffer: () => Buffer.from(sourceEdit),
                      size: () => sourceEdit.length,
                      map: () => null,
                      sourceAndMap: () => ({ source: sourceEdit, map: null }),
                      updateHash: (hash: { update(value: string): void }) => hash.update(sourceEdit),
                      buffers: () => [Buffer.from(sourceEdit)],
                      clearCache: () => undefined,
                    };
                  }
                  callback();
                });
              },
            });
          } else {
            config.plugins.push(new rspack.BannerPlugin({ banner: `${luciRequires}// WARN: generated by rsbuild - do not edit\n`, raw: true, entryOnly: true }));
            config.plugins.push(new rspack.BannerPlugin({ banner: "return main;", raw: true, entryOnly: true, footer: true }));
            config.optimization.minimize = false;
          }
          return config;
        },
      },
      performance: {
        chunkSplit: {
          strategy: "all-in-one",
        },
      },
    },
    dashboardCss: {
      plugins: [pluginSass()],
      source: {
        entry: {
          "view/fluentdashboard/index": "./web/fluentdashboard/index.css",
        },
      },
      output: {
        distPath: {
          root: outputRoot,
          css: ".",
          js: ".",
        },
        filename: {
          css: "[name].css",
          js: "[name].js",
        },
        cleanDistPath: false,
        charset: "ascii",
        minify,
      },
      tools: {
        htmlPlugin: false,
        rspack: (config) => {
          config.plugins = config.plugins || [];
          config.plugins.push({
            name: "RemoveDashboardCssEntryJsPlugin",
            apply(compiler: Compiler) {
              compiler.hooks.emit.tapAsync("RemoveDashboardCssEntryJsPlugin", (compilation, callback) => {
                delete compilation.assets["view/fluentdashboard/index.js"];
                delete compilation.assets["view/fluentdashboard/index.js.map"];
                callback();
              });
            },
          });
          return config;
        },
      },
    },
  },
});
